### ISSUE TITLE
does no read column descriptions from vo and fits files

### ISSUE THREAD

**Issue by yannick1974** [atpy/atpy#30]
Hi,

When reading a vo-table or a fits file with atpy.Table() the column descriptions are not imported. I've tested using python-vo directly and it correctly reads these descriptions.

Version used: 0.9.5.3

Cheers,

Yannick

**Comment by astrofrog** [comment]
Thanks for reporting this. I've fixed this for VO tables in 047e83bc979d5a5cb00a013b25d9a61e403d6567 and abab04fd1fd4c15e357a3b6102a2c40140452e0d. For FITS tables, things are a bit more complicated because there is no 'standard' mechanism to include column descriptions as far as I can tell. Do you have an example file that has column descriptions?

**Comment by yannick1974** [comment]
Hi Thomas.  As a matter of fact, it is corrected for VO tables.  You can find a FITS table with column descriptions there → http://hedam.oamp.fr/HerMES/data/files/DR1/catalogues/CD_Abell-2218_SCAT250_DR1.fits.gz
Thanks.
Yannick

**Comment by astrofrog** [comment]
Sorry for the delay - as discussed in this issue on PyFITS (https://trac.assembla.com/pyfits/ticket/164), TUCD and TCOMM are not in the FITS standard. It might be safest for you to just have a helper function that will go and pull out those header keywords (from t.keywords) and add them as descriptions. I'm going to close this issue, but feel free to re-open if needed.
