### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by vallis** [atpy/atpy#42]
Hello Thomas and Eli,

great work on this package!

I'm a little worried however that activity has gone done down before getting to the crucial 1.0 release; I'm loath to recommend atpy to my students if it's going to fizzle out.

Just today I was bitten by a VOtable/numpy import problem that was corrected a while ago (https://github.com/atpy/atpy/commit/4a0dd8293082feba8711). Something like that would warrant a release IMHO...

Again, I truly appreciate your work and the fact that this is open source, and could even try to help a little.

Michele

**Comment by astrofrog** [comment]
@vallis - thanks for your feedback! ATpy is still under active development (even though development has slowed down in practice, as functionality and the API have converged), and we will have a release very soon! (0.9.6)

Over the next few months, we will transition to using the Astropy package as the main dependency, which will not change the API, but will simplify the dependencies (since it will replace pyfits, vo, and asciitable). We will also ensure that the API for ATpy remains backward-compatible in this transition.

**Comment by astrofrog** [comment]
ATpy 0.9.6 was released in May, so I am going to close this issue. Let me know if you have any issues with that version!
