### ISSUE TITLE
Integrate Pandas into ATpy

### ISSUE THREAD

**Issue by ebressert** [atpy/atpy#44]
Pandas has some notable features that ATpy could use:

(copy-pasted from Pandas website)
- Easy handling of missing data (represented as NaN) in floating point as well as non-floating point data
- Powerful, flexible group by functionality to perform split-apply-combine operations on data sets, for both aggregating and transforming data
- Make it easy to convert ragged, differently-indexed data in other Python and NumPy data structures into DataFrame objects
- Intelligent label-based slicing, fancy indexing, and subsetting of large data sets
- Intuitive merging and joining data sets
- Flexible reshaping and pivoting of data sets

Would it be possible to integrate into ATpy? I'll start testing this to see if it's possible. If anyone else is interested, fork it :).

**Comment by astrofrog** [comment]
We need to see how much of this is orthogonal to moving to use the Astropy base Table class, which has some powerful slicing (thanks to @taldcroft). Would these two be incompatible?

**Comment by astrofrog** [comment]
Just for information, handling of missing data, and merging/joining is definitely something that we want to have in the Astropy table class. But it'd be cool to see what is possible with Pandas.

**Comment by taldcroft** [comment]
I've been following Pandas development and attended the tutorial at PyCon this year.  It's really a juggernaut and cannot be ignored.  

Right now there is one real issue with using this as a base for storing/manipulating tables, namely that it does not support multi-dimensional table columns.  There was a question to this effect at the tutorial and it did not sound like this was a high priority.  I've looked at the code and the way tables are stored I think this isn't so easy for Pandas.  In my own world X-ray response matrices are stored this way and there are various FITS standards that require using multidimensional columns.  So for astronomy Pandas cannot be the entire basis for storing tables.

A minor issue is lack of support for memory mapped tables, though I think this is more likely to get implemented since clearly Pandas will want to handle big data.

I have been thinking about a hybrid approach where if Pandas is installed then the Table class might use Pandas as an engine to do some of the fancy manipulations like groupby and pivoting.  This could be done for tables that don't have multidimensional columns.  It would be a bit expensive, requiring conversion from Pandas and back to Table, but that would be a relatively easy way to get a lot of functionality.

**Comment by ebressert** [comment]
Thanks for the input everyone. Tom A., it sounds like you have already done a thorough investigation on Pandas. I wonder if it would be possible to automate the way the basetable handles the input and could decide whether Pandas or Numpy arrays is best. If ATpy sees that a column will be mutli-dimensional it can then pass the Pandas table to the Numpy table. Then with your suggestion we could use Pandas for the manipulation operations if necessary. Does this sound doable?

**Comment by taldcroft** [comment]
@ebressert - I think that sounds do-able as long as you can maintain the same table UI for users in any case.  Just to be clear even though this is an ATPy issue I'm thinking about the astropy Table class since that's where I'll focus any of my development effort.  But the ideas are probably applicable in both cases given the Table heritage.

What you said makes me wonder about how hard it would be in astropy Table to allow for the internal data representation to be a Pandas object when possible while maintaining the same UI.  That would really kick-start Table in terms of functionality for the majority of use cases while maintaining our requirements about metadata (which is another thing that Pandas didn't adequately support last time I looked).  This would probably entail bundling Pandas but I don't think that would be a big problem.  Thoughts @astrofrog?  Or use the legacy package machinery to optionally install a bundled version if not already available.

**Comment by astrofrog** [comment]
I need to look into Pandas more, but another option would be to have `to_panda` and `from_panda` methods in the Table class. Since from what you said Pandas doesn't support multi-dimensional columns, having it as the default internal representation could be tricky, no?

**Comment by ebressert** [comment]
I'm following up on this discussion since it's been a while. Is there any update on whether Pandas is compatible with ATpy? Or should we just do the suggestion that @astrofrog suggests on the `to_panda` and `from_panda` functions?

**Comment by astrofrog** [comment]
I think it would be worth writing simple conversion functions to start with, which can then be incorporated as methods. However, I think new development should occur in Astropy, not ATpy. How easy is it to convert between pandas tables and Astropy tables?

**Comment by astrofrog** [comment]
I'm going to close this since I don't think new features like this should be added to ATpy, but they should be considered for Astropy tables instead. See https://github.com/astropy/astropy/issues/1156 for a discussion on this.
