### ISSUE TITLE
votable fails with recent version of astropy

### ISSUE THREAD

**Issue by hamogu** [atpy/atpy#54]
Since atpy now uses astropy for some read-in stuff, if also depends on changes in astropy.
The votable fails with a recent astropy version, because `astropy.io.vo.table` is now called `astropy.io.votable` and also the `vo.tree` module has been moved.

I do not attach a fix here, since you need to decide yourself what the future of atpy is. Will it be updated at all? If so, what version of astropy should it work with?
I imaging you spend enough time on astropy to make it worthwhile to freeze atpy at major releases, even if that means that it will not work with the current developer version...

Specifically, for my case, I have reverted to an older version before astropy. Works fine for almost anything and it's only for old code anyway...

**Comment by astrofrog** [comment]
@hamogu - I've fixed it in 07f78c74522e6c916b33d2e5fa324236ac82f424 because it doesn't make sense to have the developer version depend on a deprecated version of Astropy (Astropy 0.2 will be out soon).

The question of the future of ATpy is a good one - at the moment, not all of the functionality in ATpy is in Astropy, so we can't deprecate ATpy yet. However, if the functionality you need is already in Astropy, you should consider switching over to using the `Table` class in Astropy for new scripts (see e.g. http://docs.astropy.org/en/latest/table/io.html - ASCII, VO, and HDF5 are already built-in).

Astropy has a slightly different API for reading in tables and for adding columns, so scripts would need to be updated to make direct use of the Astropy Table class. One option for the future of ATpy that I'm considering at the moment is to make ATpy into a thin wrapper around Astropy that provides a backward-compatible API, but behind the scenes just uses the latest code.

**Comment by astrofrog** [comment]
Of course, I'd be interested in your feedback on my suggestions, given that you've developed a lot of code against ATpy :-)

**Comment by hamogu** [comment]
I did never really publicize my atpyextensions, because I always anticipated that I will transform them to astropy first.
I'll probably translate them once the coordinates are done in astropy. It's not going to be that much work, because astropy already has some of the features in other modules (I know Tom A and maybe you looked at the way I add rows in atpy when you implemented the table class).
Until then, I just keep using atpy as it is.
